config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'categories#index', as: :authenticated_root
    end

    unauthenticated do
      root 'users#index', as: :unauthenticated_root
    end
  end

  get 'categories/most_recent_list'
  get 'categories/most_ancient_list'

  resources :categories, only: %i[index new create show destroy update] do
    resources :payments, only: %i[index new create destroy update]
  end

  resources :users, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_payments
  has_many :payments, through: :category_payments

  has_one_attached :icon, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }
  validates :user_id, presence: true

  def recent_payments
    payments.order(created_at: :desc).limit(5)
  end
end

app/models/category_payment.rb
class CategoryPayment < ApplicationRecord
  belongs_to :category, class_name: 'Category'
  belongs_to :payment, class_name: 'Payment'

  validates :category_id, presence: true
  validates :payment_id, presence: true
end

app/models/concerns/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :read, User

      return unless user.present?

      can :manage, Category, user_id: user.id
      can :manage, Payment, user_id: user.id
    end
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  has_many :category_payments
  has_many :categories, through: :category_payments

  validates :name, presence: true, length: { maximum: 250 }
  validates :amount, presence: true, numericality: { greater_than: 0, less_than: 100_000_000 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :payments, dependent: :destroy
  has_many :categories, dependent: :destroy

  has_one_attached :profile_picture, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }

  def most_recent_categories
    categories.order(created_at: :desc).limit(3)
  end

  def most_ancient_categories
    categories.order(created_at: :asc).limit(3)
  end

  def admin?
    admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @user = current_user
    @categories = current_user.categories.includes(:payments).order(id: :desc)
  end

  def most_recent_list
    @user = current_user
    @categories = Category.all
  end

  def most_ancient_list
    @user = current_user
    @categories = Category.all
  end

  def new
    @catagory = Category.new
  end

  def edit; end

  def create
    add_category = current_user.categories.new(category_params)
    if add_category.save
      redirect_to categories_path, notice: 'Category was successfully added'
    else
      render :new, alert: 'Failed to add category'
    end
  end

  def destroy
    @user = current_user
    @category = Category.find(params[:id])

    if @category.destroy
      redirect_to categories_path, notice: 'Category was successfully deleted'
    else
      render :index, alert: 'Failed to delete category'
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path, notice: 'Category was successfully updated'
    else
      render :edit, alert: 'Failed to update category'
    end
  end

  def category_params
    params.permit(:name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @payments = Payment.where(category_id: @category.id)
    @total_amount = @payments.sum(:amount)
  end

  def new; end

  def edit; end

  def create
    @payments = current_user.payments.new(payment_params)

    if @payments.save
      redirect_to category_payments_path, notice: 'Payment was successfully added'
    else
      render :new, alert: 'Failed to add payment'
    end
  end

  def destroy
    @payment = Payment.find(params[:id])

    if @payment.destroy
      redirect_to categories_path, notice: 'Payment was successfully deleted'
    else
      render :index, alert: 'Failed to delete payment'
    end
  end

  private

  def payment_params
    params.permit(:name, :amount, :category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<div class="card">
    <%= render 'shared/nav' %>
    <div class="card-body top">
        <%= link_to 'Oldest', categories_most_ancient_list_path, class: 'float-end px-3 floaters mb-2' %>
        <%= link_to 'Recent', categories_most_recent_list_path, class: 'float-end px-3 floaters mb-2' %>
    </div>
</div>
<div class="card">
    <div class="card-body">
    <p>Person Finance</p>
    </div>
</div>
<div class="card bg-light text-dark">
    <% @categories.each do |category| %>
        <div class="card-body">
            <div class="m-3 bg-white category-card shadow-lg bg-body rounded">
                <% if category.icon.present? %>
                    <%= image_tag category.icon, class: "catagory-photo" %>
                <% else %>
                    <%= image_tag "category.jpg", class: "catagory-photo" %>
                <% end %>
                    <div class="trans-text">
                        <div>
                            <div class="d-flex gap-3 m-2">
                                <p class="text-start"><%= link_to category.name, category_payments_path(category_id: category.id) %></p>
                                <p class="text-start"><%= link_to '', category_payments_path(category_id: category.id), class: 'fa fa-credit-card-alt icons' %></p>
                            </div>
                            <p class="text-end"><%= l category.created_at.to_date, format: :long %></p>
                        </div>
                        <div class="delete-category">
                            <p class="fw-bold p-3">$<%= Payment.where(category_id: category.id).reduce(0) { |sum, t| sum + t.amount } %></p>
                            <%= button_to 'Delete'.html_safe, category_path(id: category.id), method: :delete, class: 'btn btn-danger' %>
                        </div>
                    </div>
            </div>
        </div>
    <% end %>
</div>
<div class="btn-wrapper d-grid gap-2 d-md-block">
  <button class="btn-main" type="button" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Add Category">
    <%= link_to 'Add Category', new_category_path %>
  </button>
</div>

app/views/categories/most_ancient_list.html.erb
<div class="card">
    <%= render 'shared/nav' %>
    <div class="card-body top">
        <%= link_to 'Oldest', categories_most_ancient_list_path, class: 'float-end px-3 floaters' %>
        <%= link_to 'Recent', categories_most_recent_list_path, class: 'float-end px-3 floaters' %>
    </div>
</div>
<div class="card">
    <div class="card-body">
    <p>Person Finance</p>
    </div>
</div>
<div class="row">
    <% @user.most_ancient_categories.each do |category| %>
        <div class="col-md-3">
            <div class="m-3 bg-white category-card">
                <% if category.icon.present? %>
                    <%= image_tag category.icon, class: "catagory-photo" %>
                <% else %>
                    <%= image_tag "category.jpg", class: "catagory-photo" %>
                <% end %>
                    <div class="trans-text">
                        <div>
                            <p class="text-start"><%= link_to category.name, category_payments_path(category_id: category.id) %></p>
                            <p class="text-end"><%= l category.created_at.to_date, format: :long %></p>
                        </div>
                        <p class="fw-bold p-3">$<%= Payment.where(category_id: category.id).reduce(0) { |sum, t| sum + t.amount } %></p>
                    </div>
            </div>
        </div>
    <% end %>
</div>
<div class="btn-wrapper d-grid gap-2 d-md-block">
  <button class="btn-main" type="button">
    <%= link_to 'Add Category', new_category_path %>
  </button>
</div>

app/views/categories/most_recent_list.html.erb
<div class="card">
    <%= render 'shared/nav' %>
    <div class="card-body top">
        <%= link_to 'Oldest', categories_most_ancient_list_path, class: 'float-end px-3 floaters' %>
        <%= link_to 'Recent', categories_most_recent_list_path, class: 'float-end px-3 floaters' %>
    </div>
</div>
<div class="card">
    <div class="card-body">
    <p>Person Finance</p>
    </div>
</div>
<div class="row">
    <% @user.most_recent_categories.each do |category| %>
        <div class="col-md-3">
            <div class="m-3 bg-white category-card">
                <% if category.icon.present? %>
                    <%= image_tag category.icon, class: "catagory-photo" %>
                <% else %>
                    <%= image_tag "category.jpg", class: "catagory-photo" %>
                <% end %>
                    <div class="trans-text">
                        <div>
                            <p class="text-start"><%= link_to category.name, category_payments_path(category_id: category.id) %></p>
                            <p class="text-end"><%= l category.created_at.to_date, format: :long %></p>
                        </div>
                        <p class="fw-bold p-3">$<%= Payment.where(category_id: category.id).reduce(0) { |sum, t| sum + t.amount } %></p>
                    </div>
            </div>
        </div>
    <% end %>
</div>
<div class="btn-wrapper d-grid gap-2 d-md-block">
  <button class="btn-main" type="button">
    <%= link_to 'Add Category', new_category_path %>
  </button>
</div>

app/views/categories/new.html.erb
<%= render 'shared/nav'%>
<div class="card">
    <div class="card-body">
        <%= form_with model: @category, url: categories_path do |f| %>
            <div class="mb-3">
                <%= f.file_field :icon, placeholder: "Add picture", class: "form-control", type:"file", id:"formFile" %>
            </div>
            <%= f.text_field :name, placeholder: "Name", class: "form-control"%>
            <%= f.submit 'Add Category', class: 'btn-form'%>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag :manifest, async: true %>
  </head>
  </head>

  <body>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/payments/index.html.erb
<%= render "shared/nav" %>
<div class="d-flex  justify-content-between">
   <%= link_to 'Back', categories_path, class: "btn btn-primary m-3"  %>
   <%= button_to "Delete", category_payment_path(category_id: @category.id, id: @category), method: :delete, class: 'bi bi-archive-fill btn btn-danger m-3' %>
</div>
<div class="card">
   <div class="card-body">
      <% if @payments.blank? %>
         <p>You Do Have Payments At the Moment </p>
      <% else %>
         <div class='top-card'>
            <% if @category.icon.present? %>
               <%= image_tag @category.icon %>
            <% else %>
               <%= image_tag "category.jpg" %>
            <% end %>
            <h1><%= @category.name %></h1>
         </div>
         <div class="border border-success p-2 border-opacity-10 mt-3">
            <p class='py-3'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
            sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
         </div>
         <hr />
         <ul>
            <% @payments.each do |payment| %>
               <li class="payments">
                  <a><%= payment.name %></a>
                  <a>$<%= payment.amount %></a>
               </li>
            <% end %>
         </ul>
         <hr />
      <% end %>
      <div class="d-flex justify-content-between">
         <p>Total Amount</p>
         <p>$<%= @total_amount %></p>
      </div>
   </div>
</div>

<div class="btn-wrapper d-grid gap-2 d-md-block">
  <button class="btn-main" type="button">
    <%= link_to "Add Transaction", new_category_payment_path %>
  </button>
</div>

app/views/payments/new.html.erb
<%= render 'shared/nav'%>
<div class="card">
  <div class="card-body">
    <%= form_with model: @catagory_payment, url: category_payments_path do |f| %>
        <%= f.text_field :name, placeholder: 'Name', class:'form-control mb-3'%>
        <%= f.number_field :amount, placeholder: 'Amount', class: 'form-control mb-3'%>
        <%= fields_for(@category) do |cat| %>
            <%= cat.select :category_id, Category.all.map { |c| [c.name, c.id] }, {}, {class: 'form-select form-select-lg mb-3'} %>
        <% end %> 
        <%= f.submit 'Add Transaction', class:'btn-form'%>
    <% end %>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="collapse" id="navbarToggleExternalContent">
  <div class="bg-primary p-2 d-flex" style="--bs-bg-opacity: .5;">
    <%= button_to "Logout", destroy_user_session_path, method: :delete , class: "btn btn-danger" %>
  </div>
</div>

<nav class="nav-main">
    <ul class="nav-items navbar navbar-expand-md">
        <button class="navbar-toggler" onclick="this.blur();" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fa fa-bars" aria-hidden="true"></i>
          </button>
        <li class="nav-item">
            <p>TRANSACTIONS</p>
        </li>
        <li class="nav-item">
            <i class="fa-solid fa-trash-can" aria-hidden="true"></i>
        </li>
    </ul>
</nav>

app/views/users/index.html.erb
<section class="splash">
  <h1 class='fst-italic fw-bold'>Mobile(B)Money</h1>
  <div class="spinner-grow text-primary" role="status">
  <span class="visually-hidden">Loading...</span>
</div>

  <div class="d-grid gap-2 col-6 mx-auto">
  <button class="btn btn-primary" type="button">
    <%= link_to "LOG IN", new_user_session_path, data: {turbo: false} %>
  </button>
  <button class="btn btn-outline-success" type="button">
    <%= link_to "SIGN UP", new_user_registration_path, data: {turbo: false} %>
  </button>
</div>

</section>